### ISSUE TITLE
DbHelper分页查询如果查询结果集为空时，会出现莫名其妙诡异的类型转换异常

### ISSUE THREAD

**Issue by ibootz** [zondaAI/DbHelper#1]
最近在使用该插件的时候，发现分页查询的时候，如果结果集是空的时候，会返回一个PageList.EMPTY_PAGE，这个静态全局final的空分页对象有一个暗坑，就是如果这个时候上层程序员不清楚底层逻辑，直接拿这个list往里面塞了某个类型的对象进去，会导致该全局对象被污染，进而导致系统出现很多莫名其妙的类型转换异常。PS：这个异常困扰了我们团队很久 。。。(╥╯^╰╥)
    如果需要修复的话，可以参考一下Collections.emptyList() 方法，Apache的该方法很显然自己声明了一个私有内部类，并且该类没有提供add方法。

**Comment by zondacker** [comment]
Thanks for you feedback. I will fix it soon.

**Comment by zondacker** [comment]
> ```
> 最近在使用该插件的时候，发现分页查询的时候，如果结果集是空的时候，会返回一个PageList.EMPTY_PAGE，这个静态全局final的空分页对象有一个暗坑，就是如果这个时候上层程序员不清楚底层逻辑，直接拿这个list往里面塞了某个类型的对象进去，会导致该全局对象被污染，进而导致系统出现很多莫名其妙的类型转换异常。PS：这个异常困扰了我们团队很久 。。。(╥╯^╰╥)
> 如果需要修复的话，可以参考一下Collections.emptyList() 方法，Apache的该方法很显然自己声明了一个私有内部类，并且该类没有提供add方法。
> ```

感谢您的反馈，Fixed
